# Generated by Django 5.1.1 on 2024-09-15 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydata',
            name='founded',
        ),
        migrations.AddField(
            model_name='companydata',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companydata',
            name='current_employee_estimate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companydata',
            name='domain',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companydata',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companydata',
            name='locality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companydata',
            name='size_range',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companydata',
            name='total_employee_estimate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companydata',
            name='year_founded',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='industry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
